version: '3'
services:
  mysql:
    container_name: db
    build: data/
    image: soa-mysql
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: ingress

  www:
      container_name: www
      build: html/
      image: soa-www
      ports:
        - "8080:80"

  rest:
      container_name: api
      build: api/
      image: soa-api
      ports:
        - "5000:5000"